-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B 
JOIN AUTHOR A USING (AUTHOR_ID)
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE LIKE '2022-01-%'
GROUP BY B.CATEGORY, B.AUTHOR_ID
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC

