-- 코드를 입력하세요
SELECT DATE_FORMAT(o.SALES_DATE, '%Y') YEAR, DATE_FORMAT(o.SALES_DATE, '%m') MONTH, u.gender, COUNT(DISTINCT o.user_id) USERS
FROM USER_INFO u
JOIN ONLINE_SALE O
USING(USER_ID)
WHERE u.gender IS NOT NULL
GROUP BY YEAR, MONTH, u.gender
ORDER BY YEAR, MONTH, u.gender