-- 코드를 작성해주세요
SELECT E.EMP_NO, EMP_NAME, 
CASE WHEN AVG(SCORE) >= 96 THEN 'S'
WHEN AVG(SCORE) >= 90 THEN 'A'
WHEN AVG(SCORE) >= 80 THEN 'B'
WHEN AVG(SCORE) < 80 THEN 'C' END
GRADE, 
CASE WHEN AVG(SCORE) >= 96 THEN SAL*0.2
WHEN AVG(SCORE) >= 90 THEN SAL*0.15
WHEN AVG(SCORE) >= 80 THEN SAL*0.1
WHEN AVG(SCORE) < 80 THEN SAL*0 END BONUS
FROM HR_EMPLOYEES E
JOIN HR_DEPARTMENT D USING(DEPT_ID)
JOIN HR_GRADE G USING(EMP_NO)
GROUP BY E.EMP_NO, EMP_NAME
ORDER BY E.EMP_NO ASC
