-- 코드를 작성해주세요
SELECT D1.ID, D1.GENOTYPE, D2.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA D1
INNER JOIN ECOLI_DATA D2
ON D1.PARENT_ID = D2.ID
WHERE D1.GENOTYPE & D2.GENOTYPE = D2.GENOTYPE
ORDER BY D1.ID ASC