-- 코드를 작성해주세요
SELECT G.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN (
    SELECT EMP_NO, SUM(SCORE) SCORE, RANK() OVER (ORDER BY SUM(SCORE) DESC) RANK_NUM
    FROM HR_GRADE
    GROUP BY EMP_NO
) G USING (EMP_NO)
WHERE G.RANK_NUM = 1;